Physical Constants
^^^^^^^^^^^^^^^^^^

.. list-table::
   :header-rows: 1
   :widths: 35 35 30

   * - Name
     - Value
     - Units
   * - ``G``
     - 6.6743e-20
     - km^3/(kg*sec^2)
   * - ``L_tilde_GR``
     - 1.480827e-08
     - unitless
   * - ``Stefan_Boltzmann``
     - 5.670374419e-08
     - kg/sec^3
   * - ``c``
     - 299792.458
     - km/sec
   * - ``gamma_GR``
     - 1.0
     - unitless
   * - ``srp_constant1``
     - 102115339416981.84
     - (kg*km)/sec^2
   * - ``srp_constant2``
     - 101979437570000.0
     - (kg*km)/sec^2

Major Bodies
^^^^^^^^^^^^^

.. list-table::
   :header-rows: 1
   :widths: 15 10 15 15 15 15 15

   * - Body
     - SPICE ID
     - Mass (kg)
     - GM (km³/s²)
     - Mean Radius (km)
     - Eq. Radius (km)
     - Primary
   * - Sun
     - 10
     - 1.9884e+30
     - 1.32712e+11
     - 696000.0
     - —
     - —
   * - Mercury
     - 199
     - 3.3010e+23
     - 22031.8
     - 2439.7
     - 2441
     - —
   * - Venus
     - 299
     - 4.8673e+24
     - 324859
     - 6051.8
     - 6052
     - —
   * - Earth
     - 399
     - 5.9722e+24
     - 398600
     - 6371.0084
     - 6378
     - —
   * - Mars
     - 499
     - 6.4169e+23
     - 42828.4
     - 3389.5
     - 3396
     - —
   * - Jupiter
     - 599
     - 1.8981e+27
     - 1.26687e+08
     - 69911.0
     - 7.149e+04
     - —
   * - Saturn
     - 699
     - 5.6832e+26
     - 3.79312e+07
     - 58232.0
     - 6.027e+04
     - —
   * - Uranus
     - 799
     - 8.6810e+25
     - 5.79395e+06
     - 25362.0
     - 2.556e+04
     - —
   * - Neptune
     - 899
     - 1.0241e+26
     - 6.8351e+06
     - 24622.0
     - 2.476e+04
     - —

Minor Bodies
^^^^^^^^^^^^^^^^^^^^^

.. list-table::
   :header-rows: 1
   :widths: 15 10 15 15 15 15 15

   * - Body
     - SPICE ID
     - Mass (kg)
     - GM (km³/s²)
     - Mean Radius (km)
     - Eq. Radius (km)
     - Primary
   * - Scheeres
     - 20008887
     - 6.2400e+14
     - 4.16e-05
     - 3.907
     - —
     - SUN
   * - Deimos
     - 402
     - 1.4407e+15
     - 9.61557e-05
     - 6.0
     - —
     - Mars
   * - McMahon
     - 20046829
     - 4.2900e+13
     - 2.86e-06
     - 1.6
     - —
     - SUN
   * - Justitia
     - 20000269
     - 1.0488e+17
     - 0.007
     - 50.728
     - —
     - SUN
   * - Mattia Pugliatti
     - 2042042
     - 6.2928e+17
     - 0.042
     - 4.2
     - —
     - SUN
   * - Moon
     - 301
     - 7.3458e+22
     - 4902.8
     - 1737.4
     - 1738
     - Earth
   * - Phobos
     - 401
     - 1.0619e+16
     - 0.000708755
     - 11.4
     - —
     - Mars
   * - Pluto
     - 999
     - 1.3029e+22
     - 869.614
     - 1195.0
     - 1195
     - —