# SPDX-FileCopyrightText: 2026 Orbital Research Cluster for Celestial Applications (ORCCA) Lab, University of Colorado at Boulder
# SPDX-License-Identifier: ISC



#-----------------------#
#        Include        #
#-----------------------#
import os
import re
import pygraphviz as pgv

#-----------------------#
#     Instructions      #
#-----------------------#

# cd src
# cd scarabaeus
# python -c "import class_connector_uml; class_connector_uml.edit_dot_file()"


#method
def get_file_dict():
    '''
    A function to get the dictionary of all the modules and submodules within the src directory
    '''
    folder_names = ['body', 'dynamics', 'environment', 'guidance', 'measurements',
                    'orbitDetermination', 'spacecraft', 'timeAndFrame', 'units', 'utils']
    file_dict ={}
    for folder in folder_names:
        # get the names of every file in the folder
        files = os.listdir(f'../src/scarabaeus/{folder}')
        # remove pycache from the list
        files.remove('__pycache__')
        files = [val[:-3] if val.endswith(".py") else val for val in files]
        files = [val for val in files if not val.startswith("__init__")]
        file_dict[folder]= files
    return file_dict

#method
def assign_parent(module):
    '''
    To assign the parent directory based on the submodule
    '''
    file_dict = get_file_dict()
    folder = ""
    for key in file_dict.keys():
        if module in file_dict[key]:
            folder = key
    return f'scarabaeus.{folder}.{module}.{module}'

#method
def find_connections():
    '''
    To scan all the submodules and find the relationship between the classes at the function level.
    '''
    folder_names = ['body', 'dynamics', 'environment', 'guidance', 'measurements',
                    'orbitDetermination', 'spacecraft', 'timeAndFrame', 'units', 'utils']
    main_result=[]
    for folder in folder_names:
        # get the names of every file in the folder
        files = os.listdir(f'../src/scarabaeus/{folder}')
        # remove pycache from the list
        files.remove('__pycache__')
        results = []
        # scan each file
        for module in files:
            # read in the file
            file_path = os.path.dirname(os.getcwd()) + f'/src/scarabaeus/{folder}/{module}'
            with open(file_path, 'r') as file:
                file_content = file.read()
            # find every occurance of scb
            all_occurances = re.findall(r'scb.\S+?\S+', file_content)
            scb_occurances = []
            for occurance in all_occurances:
                occurance = occurance.replace("scb.","").replace("scb ","").replace(",","").replace(":","")
                occurance = occurance.split('.')[0]
                occurance = occurance.split('(')[0]
                occurance = occurance.split(')')[0]
                scb_occurances.append(occurance)
            scb_occurances = list(set(scb_occurances))
            scb_occurances = [assign_parent(val) for val in scb_occurances]
            scb_occurances = [element for element in scb_occurances if '..' not in element]
            if len(scb_occurances) >0:
                scb_occurances = [f"{assign_parent(module[:-3])}", scb_occurances]
                results.append(scb_occurances)
        main_result.append(results)
    flattened_result = [item for sublist in main_result for item in sublist]
    flattened_dict ={}
    for val in flattened_result:
        if val[0] in flattened_dict.keys():
            temp = flattened_dict[val[0]]
            flattened_dict[val[0]] = list(set(temp + val[1]))
        else:
            flattened_dict[val[0]] = val[1]
    return flattened_dict


#method
def edit_dot_file():
    '''
    To edit the DOT file with the function level relationship generated by the "find_connections()".
    '''
    connection_dict = find_connections()
    # Template for the DOT format
    dot_template = '"{source}" -> "{target}" [arrowhead="empty", arrowtail="none", fontcolor="red", label="functional relation"];'
    # Iterate through the dictionary and create the DOT format for each relation
    template_string = []
    for source, targets in connection_dict.items():
        for target in targets:
            # Format each relation using the template
            dot_output = dot_template.format(source=source, target=target)
            template_string.append(dot_output)
    #open the DOT file
    dot_path = '../src/classes.dot'
    with open(dot_path, 'r') as file:
        content = file.read()
    last_curly_pos = content.rfind('}')
    if last_curly_pos != -1:
        # Remove the last closing curly brace from the content
        content = content[:last_curly_pos]
        new_content = '\n'.join(template_string)
        # Append new elements and then re-add the closing curly brace
        content += "\n"+ new_content+ '\n}'
        # Write the updated content back to the file
        with open(dot_path, 'w') as file:
            file.write(content)
